# Generated by Django 5.2 on 2025-05-09 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja_app', '0005_produto_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='slug',
        ),
    ]
