# Generated by Django 5.2 on 2025-06-27 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja_app', '0006_remove_produto_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='total',
        ),
    ]
