# Generated by Django 5.2 on 2025-06-29 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja_app', '0007_remove_pedido_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
