# Generated by Django 5.2 on 2025-07-04 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja_app', '0008_pedido_finalizado'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoNutricional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.PositiveIntegerField()),
                ('sexo', models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino')], max_length=10)),
                ('contato', models.CharField(blank=True, max_length=100)),
                ('peso_atual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=4)),
                ('peso_desejado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('atividade_fisica', models.BooleanField()),
                ('doenca', models.TextField(blank=True)),
                ('medicacao', models.TextField(blank=True)),
                ('sono', models.PositiveIntegerField()),
                ('estresse', models.PositiveIntegerField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
